version: "3"
services:
  spider:
    build: .
    depends_on:
      - "db"
    command: ["./wait-for-it.sh", "db:3306", "--", "python", "main.py"]
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./:/app
  db:
    image: 'mysql:5.7'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 3ctMcfmlKKPwwNaI # 此处不对外开放端口，认为mysql较为安全
      TZ: Asia/Shanghai

  grafana:
    image: grafana/grafana:8.1.1
    ports:
      - "8899:3000"
    volumes:
    - ./grafana.ini:/etc/grafana/grafana.ini




